name: Test

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.23"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: make test

      - name: Build
        run: make build
